spring.application.name=projeto

# Configuracoes do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/audio
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Outras configuracoes opcionais
server.port=8080
